name: Build AllTrans (legacy AGP)

on:
  workflow_dispatch:        # 手动触发，避免每次 push 都跑
  push:
    paths: ["**/*.java", "**/*.xml", "**/*.gradle"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # 用 JDK 8，避免 JAXB 缺失
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
          cache: gradle

      # 自己装旧版 cmdline-tools + platform 30 + build-tools 30.0.3
      - name: Install Android SDK 30
        shell: bash
        env:
          ANDROID_SDK_ROOT: ${{ runner.tool_cache }}/android-sdk
        run: |
          mkdir -p $ANDROID_SDK_ROOT
          cd $ANDROID_SDK_ROOT
          curl -sSLo cmdline.zip https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
          unzip -q cmdline.zip -d cmdline
          yes | cmdline/tools/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
              "platform-tools" \
              "platforms;android-30" \
              "build-tools;30.0.3"

      # 生成 local.properties
      - run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      # 使用仓库内 Gradle Wrapper (5.1.1)
      - name: Build APKs
        run: ./gradlew :app:assembleRelease :module:assembleRelease --no-daemon --stacktrace

      - uses: actions/upload-artifact@v3
        with:
          name: APK
          path: |
            app/build/outputs/apk/release/*.apk
            module/build/outputs/apk/release/*.apk