name: Build Release APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create fixed XML files
      run: |
        echo "=== 创建修复后的XML文件 ==="
        
        # 1. 修复 apps_list.xml
        cat > app/src/main/res/layout/apps_list.xml << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<!--
  ~ Copyright 2017 Akhil Kedia
  ~ This file is part of AllTrans.
  ~
  ~ AllTrans is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ AllTrans is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with AllTrans. If not, see <http://www.gnu.org/licenses/>.
  ~
  -->

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">
    <android.widget.ListView
        android:id="@+id/AppsList"
        style="@android:style/Widget.DeviceDefault.Light.ListView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:headerDividersEnabled="false" />
</LinearLayout>
EOF
        
        # 2. 修复 strings.xml - 只添加结束标签
        if ! grep -q "</resources>" app/src/main/res/values/strings.xml; then
            echo "</resources>" >> app/src/main/res/values/strings.xml
        fi
        
        # 3. 创建 keys.xml
        cat > app/src/main/res/values/keys.xml << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<resources>
</resources>
EOF
        
        # 4. 创建 ic_list_icon_placeholder.xml
        mkdir -p app/src/main/res/drawable-anydpi-v4
        cat > app/src/main/res/drawable-anydpi-v4/ic_list_icon_placeholder.xml << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24"
    android:tint="?attr/colorOnSurface">
    <path
        android:fillColor="@android:color/white"
        android:pathData="M12,2C6.48,2 2,6.48 2,12s4.48,10 10,10 10,-4.48 10,-10S17.52,2 12,2zM13,17h-2v-6h2v6zM13,9h-2L11,7h2v2z"/>
</vector>
EOF
        
        echo "=== XML 文件创建完成 ==="
    
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup build environment
      run: |
        keytool -genkey -v -keystore release.keystore -alias key -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Android,O=Android,C=US"
        
        echo "RELEASE_STORE_FILE=../release.keystore" >> gradle.properties
        echo "RELEASE_STORE_PASSWORD=android" >> gradle.properties
        echo "RELEASE_KEY_ALIAS=key" >> gradle.properties
        echo "RELEASE_KEY_PASSWORD=android" >> gradle.properties
        echo "android.useAndroidX=true" >> gradle.properties
        echo "android.enableJetifier=true" >> gradle.properties
        
        echo '{"project_info":{"project_number":"1","project_id":"d"},"client":[{"client_info":{"mobilesdk_app_id":"1:1:android:1","android_client_info":{"package_name":"akhil.alltrans"}},"api_key":[{"current_key":"x"}]}]}' > app/google-services.json
        
        chmod +x gradlew
    
    - name: Build Release
      run: ./gradlew assembleRelease
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: alltrans-release
        path: app/build/outputs/apk/release/app-release.apk
