name: Build AllTrans (AGP 8.x + JDK17)

on: [push]          # 推上来就跑；想换触发方式自己改

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉代码
      - uses: actions/checkout@v4

      # 2. 用 JDK 17（AGP 8.x 官方要求）
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # 3. 告诉 Gradle Android SDK 路径（Runner 自带）
      - name: create local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

      # ===== 如需正式签名，取消下面整块注释，并把 4 个 secret 配好 =====
      # - name: decode keystore & write gradle.properties
      #   if: ${{ secrets.KEYSTORE_B64 != '' }}
      #   env:
      #     KEYSTORE_B64: ${{ secrets.KEYSTORE_B64 }}
      #     KEY_ALIAS:     ${{ secrets.KEY_ALIAS }}
      #     KEY_STORE_PWD: ${{ secrets.KEY_STORE_PWD }}
      #     KEY_PWD:       ${{ secrets.KEY_PWD }}
      #   run: |
      #     echo "$KEYSTORE_B64" | base64 -d > keystore.jks
      #     cat >> gradle.properties <<EOF
      #     RELEASE_STORE_FILE=keystore.jks
      #     RELEASE_STORE_PASSWORD=$KEY_STORE_PWD
      #     RELEASE_KEY_ALIAS=$KEY_ALIAS
      #     RELEASE_KEY_PASSWORD=$KEY_PWD
      #     EOF
      # =================================================================

      # 4. 构建 app & module Release APK
      - name: Build APK
        run: ./gradlew :app:assembleRelease :module:assembleRelease --no-daemon --stacktrace

      # 5. 上传产物
      - uses: actions/upload-artifact@v4
        with:
          name: APK
          path: |
            app/build/outputs/apk/release/*.apk
            module/build/outputs/apk/release/*.apk