name: Build AllTrans (legacy AGP)

on:
  workflow_dispatch:
  push:
    paths: ["**/*.java", "**/*.xml", "**/*.gradle"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉代码
      - uses: actions/checkout@v4

      # 2. JDK 8
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: gradle

      # 3. 告诉 Gradle SDK 在哪（GitHub 镜像机自带 /usr/local/lib/android/sdk）
      - name: Generate local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk   # 这个变量 Runner 默认已设置

      # 4. 编译
      - name: Build APKs
        run: ./gradlew :app:assembleRelease :module:assembleRelease --no-daemon --stacktrace

      # 5. 上传
      - uses: actions/upload-artifact@v4
        with:
          name: APK
          path: |
            app/build/outputs/apk/release/*.apk
            module/build/outputs/apk/release/*.apk