name: Build AllTrans (AGP 8.x)

on: [push]     # 每次推送自动跑；按需改成 main 分支或 PR 触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. checkout
      - uses: actions/checkout@v4

      # 2. 配 JDK 17（也可以 11；17 是 AGP 官方推荐）
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # 3. Android SDK：Runner 本身已自带 33 / 34 的平台和 34.0.0 build-tools；
      #    只需给 gradle 写个 local.properties 即可
      - name: Generate local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

      # 4. 如果你的 compileSdkVersion 低于 33，或者需要特定 buildTools，可以在这里额外装：
      # - name: Ensure platform 34 & build-tools 34.0.0
      #   run: yes | sdkmanager "platforms;android-34" "build-tools;34.0.0"

      # 5. build
      - name: Build APKs
        run: ./gradlew :app:assembleRelease :module:assembleRelease --no-daemon --stacktrace

      # 6. upload
      - uses: actions/upload-artifact@v4
        with:
          name: APK
          path: |
            app/build/outputs/apk/release/*.apk
            module/build/outputs/apk/release/*.apk