name: Build AllTrans Debug

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          
      - name: Setup gradle and fix signing
        run: |
          echo "sdk.dir=/usr/local/lib/android/sdk" > local.properties
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties
          echo "org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m" >> gradle.properties
          # 创建临时keystore
          keytool -genkey -v -keystore dummy.jks -keyalg RSA -keysize 2048 -validity 10000 -alias dummy -storepass dummy -keypass dummy -dname "CN=test, O=test, L=test, S=test, C=US"
          
      - name: Build Debug APK
        env:
          GRADLE_OPTS: -Xmx4g -XX:MaxMetaspaceSize=512m
          RELEASE_STORE_FILE: dummy.jks
          RELEASE_STORE_PASSWORD: dummy
          RELEASE_KEY_ALIAS: dummy
          RELEASE_KEY_PASSWORD: dummy
        run: ./gradlew :app:assembleDebug --no-daemon --stacktrace
        
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk