name: Build Release APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Fix XML files
      run: |
        # 修复 strings.xml
        if ! tail -1 app/src/main/res/values/strings.xml | grep -q "</resources>"; then
          echo "Adding missing </resources> tag to strings.xml"
          echo "</resources>" >> app/src/main/res/values/strings.xml
        fi
        
        # 修复 keys.xml - 重新创建一个干净的文件
        echo "Fixing keys.xml..."
        if [ -f "app/src/main/res/values/keys.xml" ]; then
          # 备份原文件
          cp app/src/main/res/values/keys.xml app/src/main/res/values/keys.xml.bak
          
          # 创建一个干净的 keys.xml
          cat > app/src/main/res/values/keys.xml << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <!-- API Keys will be added here if needed -->
</resources>
EOF
        fi
        
        echo "XML files fixed!"
    
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup build environment
      run: |
        keytool -genkey -v -keystore release.keystore -alias key -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Android,O=Android,C=US"
        
        echo "RELEASE_STORE_FILE=../release.keystore" >> gradle.properties
        echo "RELEASE_STORE_PASSWORD=android" >> gradle.properties
        echo "RELEASE_KEY_ALIAS=key" >> gradle.properties
        echo "RELEASE_KEY_PASSWORD=android" >> gradle.properties
        echo "android.useAndroidX=true" >> gradle.properties
        echo "android.enableJetifier=true" >> gradle.properties
        
        echo '{"project_info":{"project_number":"1","project_id":"d"},"client":[{"client_info":{"mobilesdk_app_id":"1:1:android:1","android_client_info":{"package_name":"akhil.alltrans"}},"api_key":[{"current_key":"x"}]}]}' > app/google-services.json
        
        chmod +x gradlew
    
    - name: Build Release
      run: ./gradlew assembleRelease
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: alltrans-release
        path: app/build/outputs/apk/release/app-release.apk
